%{~ if config.addon_config.enable_ingress_nginx }
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./addons/ingress-nginx
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
%{~ endif }
%{~ if config.addon_config.enable_metrics_server }
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./addons/metrics-server
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
%{~ endif }
%{~ if config.addon_config.enable_observability }
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: observability
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./addons/observability
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
%{~ endif }
%{~ if config.addon_config.enable_cert_manager }
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./addons/cert-manager
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
%{~ endif }
